
//=============================================================================
.external F_SACM_Initial
.external F_SACM_Play
.external F_SACM_Stop
.external F_SACM_Volume
.external F_SACM_Pause
.external F_SACM_Resume
.external F_SACM_Speed
.external F_SACM_Status
.external F_SACM_ServiceLoop
.external F_ISR_Service_SACM_DAC

//=================================	//DVR
.external F_SACM_Rec
.external F_ISR_Service_SACM_ADC
//========================================