//==========================================================================
//SACM_XXXX_SPEED.inc:  This file includes declarations and constants for SACM 
//                   Playback API . 
//                   It is to be prepared by design deptartment.  
//     XXXX: name of Algorism   
//           
//  Proposed by: Arthur
// Written by Sam Sung, 2003/01/28
//==========================================================================

/////////////////////
////////////////////	//s480 speed
//.external	F_SACM_XXXX_Speed_Initial  
.external	F_SACM_XXXX_Speed_Initial_Psuedo //add by benwang 20060120
//.external	F_SACM_XXXX_Speed_Process
.external	F_SACM_XXXX_Speed_Process_Psuedo //add by benwang 20060120
//========================================================================================        
// End of SACM_XXXX_SPEED.inc
//========================================================================================