.ifndef _SYSTEM_HEAD_INC_
.define _SYSTEM_HEAD_INC_

.include .\System\include\System\GPL162002.inc
.include .\System\include\System\GPL162001ISR.inc
.include .\System\include\WaitMode\SysWaitMode.inc
.include .\System\include\System\ophw.inc
.include .\System\include\Message\Message.inc
.include .\System\include\system\SysException.inc
.include .\system\include\system\unSPMACRO.inc

.endif
